FROM openjdk:17
LABEL maintainer="123@gmail.com"
ADD target/demo-good-bye-world-0.0.2-SNAPSHOT.jar demo-good-bye-world-0.0.2-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar","demo-good-bye-world-0.0.2-SNAPSHOT.jar"]
EXPOSE 8095