server:
  port: 8100

spring.datasource:
  driverClassName: "org.postgresql.Driver"
  url: "jdbc:postgresql://localhost:5432/mtr"
  username: "postgres"
  password: "admin1234"
  
spring.jpa:
  show-sql: true
  hibernate.ddl-auto: update
